---
~/work:
  name: Daniel Schmidt
  email: dschmidt@d2iq.com
  signingkey: D013FA3C4F430A7C80BDBFC501CE2A1CBB0DA9BF

~/fun:
  name: Daniel Schmidt
  email: danielmschmidt92@gmail.com
  signingkey: B77B63D6AD7F1D4899CE5637377C3A4D62FBBBE2
