~/work:
  name: Daniel Schmidt
  email: danielmschmidt92@gmail.com
  signingkey: B77B63D6AD7F1D4899CE5637377C3A4D62FBBBE2
~/:
  name: Daniel Schmidt
  email: danielmschmidt92@gmail.com
  signingkey: B77B63D6AD7F1D4899CE5637377C3A4D62FBBBE2
