---
- hosts: all
  connection: local

  tasks:
    # Config directory should symlink all files
    - name: Create config directory
      file:
        path: ~/.config
        state: directory
    - name: Symlink top-level config files
      file:
        dest: ~/.config/{{ item }}
        src: "{{ playbook_dir }}/dotfiles/.config/{{ item }}"
        state: link
        force: true
      loop:
        - iterm2-settings
        - tmuxconf
        - nova.itermcolors
        - vimrc
        - .gitconfig

    - name: Create fish config directory
      file:
        path: ~/.config/fish
        state: directory
    - name: Symlink fish config files
      file:
        dest: ~/.config/fish/{{ item }}
        src: "{{ playbook_dir }}/dotfiles/.config/fish/{{ item }}"
        state: link
        force: true
      loop:
        - config.fish
        - fish_variables

    - name: Create fish sub-config directory
      file:
        path: ~/.config/fish/{{ item }}
        state: directory
      loop:
        - conf.d
        - functions
    - name: Symlink fish sub-config files
      file:
        dest: ~/.config/fish/{{ item }}
        src: "{{ playbook_dir }}/dotfiles/.config/fish/{{ item }}"
        state: link
        force: true
      loop:
        - conf.d/1password.fish
        - conf.d/cdktf.fish
        - conf.d/gh.fish
        - conf.d/golang.fish
        - conf.d/kubernetes.fish
        - conf.d/node.fish
        - conf.d/nova.fish
        - conf.d/ruby.fish
        - conf.d/rust.fish
        - functions/dancing.fish

    - name: Create shell directory
      file:
        path: ~/.config/iterm2
        state: directory
    - name: Symlink iterm2 config file
      file:
        dest: ~/.config/iterm2/com.googlecode.iterm2.plist
        src: "{{ playbook_dir }}/dotfiles/.config/fish/com.googlecode.iterm2.plist"
        state: link
        force: true

    - name: Create work directory
      file:
        path: ~/work
        state: directory

    - name: Create fun directory
      file:
        path: ~/fun
        state: directory

    - name: Create go directory
      file:
        path: $HOME/go
        state: directory

    - name: Create go/bin directory
      file:
        path: $HOME/go/bin
        state: directory

    - name: Create go/src directory
      file:
        path: $HOME/go/src
        state: directory

    - name: Create go/pkg directory
      file:
        path: $HOME/go/pkg
        state: directory

    - name: Copy config files
      copy:
        src: ./dotfiles/
        dest: ~/
        force: yes

    - name: Ensure fish can be used as shell
      ansible.builtin.lineinfile:
        path: /etc/shells
        line: /usr/local/bin/fish
      become: true
