---
- hosts: all
  connection: local

  roles:
    ## Basics
    - role: fish
      theme: bobthefish
      editor: /usr/local/bin/vim
    - git
    - git-duet

  # Config directory
  tasks:
    - name: Create config directory
      file:
        path: ~/.config
        state: directory
    - name: Copy config files
      copy:
        src: ./dotfiles
        dest: ~/.config
    - name: Symlink git config
      file:
        src: "{{playbook_dir}}/dotfiles/.gitconfig"
        dest: ~/.config/.gitconfig
        state: link
