---
- hosts: all
  connection: local

  roles:
    ## Basics
    - role: fish
      theme: bobthefish
      editor: /usr/local/bin/vim
    - git
    # - git-duet
    # - role: rust
    #   rust_version: 1.51.0
    #   rust_update: true
    #   cargo_items:
    #     - wasm-pack
    # TODO: add wasm target to role

  # Config directory
  tasks:
    - name: Create config directory
      file:
        path: ~/.config
        state: directory

    - name: Create work directory
      file:
        path: ~/work
        state: directory

    - name: Create fun directory
      file:
        path: ~/fun
        state: directory

    - name: Copy config files
      copy:
        src: ./dotfiles/
        dest: ~/
        force: yes

    - name: Symlink git config
      file:
        src: "{{ playbook_dir }}/linkedfiles/.gitconfig"
        dest: ~/.gitconfig
        state: link

    # Built from gpg-key-signing branch on https://github.com/danielmschmidt/karn
    # - name: Symlink Karn binary
    #   file:
    #     src: "{{ playbook_dir }}/linkedfiles/karn"
    #     dest: /usr/local/bin/karn
    #     state: link

    - name: create GO bin folder
      file: 
        path: ~/go/bin
        state: directory
