---
- hosts: all
  connection: local

  tasks:
    # Config directory should symlink all files
    - name: Create config directory
      file:
        path: ~/.config
        state: directory
    - name: Symlink top-level config files
      file:
        dest: ~/.config/{{ item }}
        src: "{{ playbook_dir }}/dotfiles/.config/{{ item }}"
        state: link
      loop:
        - com.googlecode.iterm2.plist
        - iterm2-settings
        - tmuxconf
        - vimrc
        - .gitconfig
    - name: Create fish config directory
      file:
        path: ~/.config/fish
        state: directory
    - name: Symlink fish config files
      file:
        dest: ~/.config/fish/{{ item }}
        src: "{{ playbook_dir }}/dotfiles/.config/fish/{{ item }}"
        state: link
      loop:
        - config.fish
        - fish_variables
    - name: Create fish sub-config directory
      file:
        path: ~/.config/fish/{{ item }}
        state: directory
      loop:
        - conf.d
        - functions
    - name: Symlink fish sub-config files
      file:
        dest: ~/.config/fish/{{ item }}
        src: "{{ playbook_dir }}/dotfiles/.config/fish/{{ item }}"
        state: link
      loop:
        - conf.d/cdktf.fish
        - conf.d/golang.fish
        - conf.d/kubernetes.fish
        - conf.d/nova.fish
        - conf.d/nvm.fish
        - conf.d/ruby.fish
        - conf.d/rust.fish
        - functions/dancing.fish
        - functions/load_nvm.fish
        - functions/nvm_find_nvmrc.fish
        - functions/nvm.fish

    - name: Create work directory
      file:
        path: ~/work
        state: directory

    - name: Create fun directory
      file:
        path: ~/fun
        state: directory

    - name: Create go directory
      file:
        path: $HOME/go
        state: directory

    - name: Create go/bin directory
      file:
        path: $HOME/go/bin
        state: directory

    - name: Create go/src directory
      file:
        path: $HOME/go/src
        state: directory

    - name: Create go/pkg directory
      file:
        path: $HOME/go/pkg
        state: directory

    - name: Copy config files
      copy:
        src: ./dotfiles/
        dest: ~/
        force: yes
