tap "bazelbuild/tap"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "git-duet/tap"
tap "github/gh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazydocker"
tap "kudobuilder/tap"
tap "weaveworks/tap"

brew "openssl@1.1"
brew "ansible"
brew "bash"
brew "emacs", restart_service: true
brew "cask"
brew "composer"
brew "dcos-cli"
brew "editorconfig"
brew "ffmpeg"
brew "fish"
brew "gh"
brew "git"
brew "git-extras"
brew "gnupg"
brew "go"
brew "helm"
brew "jq"
brew "karn"
brew "kubernetes-cli"
brew "kubectx"
brew "kustomize"
brew "mas"
brew "mtr"
brew "node"
brew "nvm"
brew "openjdk"
brew "parallel"
brew "php"
brew "pipenv"
brew "postgresql"
brew "pre-commit"
brew "qrencode"
brew "redis"
brew "ripgrep"
brew "ruby"
brew "rustup"
brew "shellcheck"
brew "shfmt"
brew "skaffold"
brew "termtosvg"
brew "terraform"
brew "terraform-docs"
brew "terraform-inventory"
brew "tldr"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "xgboost"
brew "yamllint"
brew "yq"
brew "z"
brew "git-duet/tap/git-duet"

cask "1password"
cask "alfred"
cask "banking-4"
cask "caffeine"
cask "docker"
cask "flux"
cask "flycut"
cask "font-hack-nerd-font"
cask "franz"
cask "github"
cask "google-chrome"
cask "google-chrome-canary"
cask "iterm2"
cask "minikube"
cask "monodraw"
cask "notion"
cask "pocket-casts"
cask "portfolioperformance"
cask "postman"
cask "rescuetime"
cask "spectacle"
cask "spotify"
cask "visual-studio-code"
cask "vlc-nightly"

mas "Cleaner-App", id: 1013897218
mas "GIPHY CAPTURE", id: 668208984
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "MoneyMoney", id: 872698314
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
