tap "bazelbuild/tap"
tap "github/gh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "kudobuilder/tap"
tap "weaveworks/tap"
brew "openssl@1.1"
brew "ansible"
brew "awscli"
brew "bash"
brew "bazel"
brew "glib"
brew "emacs", restart_service: true
brew "cask"
brew "faas-cli"
brew "ffmpeg"
brew "fish"
brew "gh"
brew "git"
brew "git-extras"
brew "libusb"
brew "gnupg"
brew "go"
brew "helm"
brew "jq"
brew "krb5"
brew "mas"
brew "maven"
brew "mtr"
brew "node"
brew "numpy"
brew "nvm"
brew "parallel"
brew "pipenv"
brew "postgresql"
brew "pre-commit"
brew "pybind11"
brew "qrencode"
brew "redis"
brew "ripgrep"
brew "ruby"
brew "rustup-init"
brew "scipy"
brew "shfmt"
brew "skaffold"
brew "terraform"
brew "terraform-docs"
brew "terraform-inventory"
brew "tldr"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "xgboost"
brew "yq"
brew "z"
brew "heroku/brew/heroku"
cask "1password"
cask "alfred"
cask "banking-4"
cask "caffeine"
cask "discord"
cask "docker"
cask "flux"
cask "flycut"
cask "focusrite-control"
cask "font-hack-nerd-font"
cask "github"
cask "google-chrome"
cask "google-chrome-canary"
cask "google-cloud-sdk"
cask "iterm2"
cask "monodraw"
cask "notion"
cask "obs"
cask "pocket-casts"
cask "portfolioperformance"
cask "postman"
cask "rescuetime"
cask "skype"
cask "slack"
cask "spectacle"
cask "spotify"
cask "switchresx"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc-nightly"
cask "zoom"
cask "zsa-wally"
mas "Cleaner-App", id: 1013897218
mas "Focus To-Do", id: 1258530160
mas "GarageBand", id: 682658836
mas "GIPHY CAPTURE", id: 668208984
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "MoneyMoney", id: 872698314
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
